services:

  app:
    container_name: store
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -b '0.0.0.0'
    ports:
      - "4000:3000"
    volumes:
      - .:/app
      - /app/tmp
      - /app/log
    environment:
      - RAILS_ENV=development
    depends_on:
      - mysql
    develop:
      watch:
        - action: rebuild
          path: .
  mysql:
    image: mysql:8.0.35
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    ports:
      - "3307:3307"
    volumes:
      - data_database:/var/lib/mysql
    restart: unless-stopped
    command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password --port=3307

volumes:
    data_database:
      driver: local
