services:
  store:
    container_name: 
      store
    build:
      context: .    
    ports:
      - 8010:8010
    volumes:
      - .:/opt/app
    env_file:
      - .env
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0.35
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    ports:
      - "3305:3305"
    volumes:
      - data_database:/var/lib/mysql
    restart: unless-stopped
    command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password --port=3305  
    
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - store
    ports:
      - "8020:8020"

volumes:
  data_database:
  data_redis:
    driver: local
